### Items Index
GET http://localhost:3000/items.json

### Items Create
POST http://localhost:3000/items.json
Content-Type: application/json

{
"name": "test name",
"price": 50,
"description": "ok",
"voltage": 59
}

### Items Show
GET http://localhost:3000/items/1

### Items Update
PATCH http://localhost:3000/items/1
Content-Type: application/json

{
  "name": "test_name_2",
  "price": 70
}

### Items Destroy
DELETE http://localhost:3000/items/1.json

